'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PnnTemas
    
    '''<summary>
    '''ralLoad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ralLoad As Global.Telerik.Web.UI.RadAjaxLoadingPanel
    
    '''<summary>
    '''ramManajer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ramManajer As Global.Telerik.Web.UI.RadAjaxManager
    
    '''<summary>
    '''rapContenedor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rapContenedor As Global.Telerik.Web.UI.RadAjaxPanel
    
    '''<summary>
    '''btnCuentas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCuentas As Global.Telerik.Web.UI.RadToolBar
    
    '''<summary>
    '''RadTabStrip1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTabStrip1 As Global.Telerik.Web.UI.RadTabStrip
    
    '''<summary>
    '''RadMultiPage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadMultiPage1 As Global.Telerik.Web.UI.RadMultiPage
    
    '''<summary>
    '''RadPageView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView1 As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''RadGrid2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGrid2 As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''RadProgressBar1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadProgressBar1 As Global.Telerik.Web.UI.RadProgressBar
    
    '''<summary>
    '''RadProgressBar2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadProgressBar2 As Global.Telerik.Web.UI.RadProgressBar
    
    '''<summary>
    '''RadLabel127 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel127 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox14 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel2 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox2 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel3 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox3 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel4 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDropDownList1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDropDownList1 As Global.Telerik.Web.UI.RadDropDownList
    
    '''<summary>
    '''RadLabel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel5 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadLabel6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel6 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadLabel7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel7 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadLabel11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel11 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDatePicker1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker1 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadLabel12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel12 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDatePicker2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker2 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadCheckBox3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox3 As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''RadLabel13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel13 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadCheckBox4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox4 As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''RadLabel14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel14 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadLabel15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel15 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadLabel16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel16 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDropDownList3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDropDownList3 As Global.Telerik.Web.UI.RadDropDownList
    
    '''<summary>
    '''RadLabel17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel17 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDropDownList13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDropDownList13 As Global.Telerik.Web.UI.RadDropDownList
    
    '''<summary>
    '''RadLabel18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel18 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDropDownList14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDropDownList14 As Global.Telerik.Web.UI.RadDropDownList
    
    '''<summary>
    '''RadLabel19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel19 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadLabel20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel20 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadLabel118 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel118 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox57 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox57 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadPageView2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView2 As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''RadLabel45 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel45 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadProgressBar3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadProgressBar3 As Global.Telerik.Web.UI.RadProgressBar
    
    '''<summary>
    '''RadProgressBar4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadProgressBar4 As Global.Telerik.Web.UI.RadProgressBar
    
    '''<summary>
    '''CheckBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''RadLabel8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel8 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''CheckBox2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox2 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''RadLabel9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel9 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadLabel10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel10 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox6 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel21 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox7 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel22 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox8 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel23 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox9 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel46 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel46 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDropDownList5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDropDownList5 As Global.Telerik.Web.UI.RadDropDownList
    
    '''<summary>
    '''RadLabel24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel24 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''FileUpload1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUpload1 As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''RadLabel25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel25 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox10 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''btnTtema control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTtema As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''RadLabel44 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel44 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadLabel35 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel35 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDropDownList4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDropDownList4 As Global.Telerik.Web.UI.RadDropDownList
    
    '''<summary>
    '''RadLabel36 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel36 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDatePicker7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker7 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadLabel37 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel37 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDatePicker8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker8 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadLabel38 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel38 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadLabel39 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel39 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDatePicker9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker9 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''FileUpload3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUpload3 As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''RadLabel40 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel40 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDatePicker10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker10 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadLabel41 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel41 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadioButton7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButton7 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadioButton8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButton8 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadLabel42 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel42 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadLabel43 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel43 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadioButton11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButton11 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadioButton12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButton12 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadioButton9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButton9 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadioButton10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButton10 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadPageView3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView3 As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''RadLabel26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel26 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadProgressBar5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadProgressBar5 As Global.Telerik.Web.UI.RadProgressBar
    
    '''<summary>
    '''RadProgressBar6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadProgressBar6 As Global.Telerik.Web.UI.RadProgressBar
    
    '''<summary>
    '''RadLabel27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel27 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox11 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel28 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox12 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel29 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox13 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel30 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDropDownList2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDropDownList2 As Global.Telerik.Web.UI.RadDropDownList
    
    '''<summary>
    '''RadLabel31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel31 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadLabel32 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel32 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDatePicker20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker20 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadLabel33 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel33 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDatePicker21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker21 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadLabel34 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel34 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''FileUpload2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUpload2 As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''RadLabel47 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel47 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDatePicker22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker22 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadLabel48 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel48 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadioButton1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButton1 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadioButton2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButton2 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadLabel49 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel49 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDatePicker23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker23 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadLabel50 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel50 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''FileUpload4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUpload4 As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''RadLabel51 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel51 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDatePicker24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker24 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadLabel52 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel52 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''FileUpload5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUpload5 As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''RadLabel53 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel53 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDatePicker25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker25 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadButton2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadButton2 As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''RadPageView4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView4 As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''RadProgressBar7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadProgressBar7 As Global.Telerik.Web.UI.RadProgressBar
    
    '''<summary>
    '''RadProgressBar8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadProgressBar8 As Global.Telerik.Web.UI.RadProgressBar
    
    '''<summary>
    '''RadTabStrip2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTabStrip2 As Global.Telerik.Web.UI.RadTabStrip
    
    '''<summary>
    '''RadMultiPage2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadMultiPage2 As Global.Telerik.Web.UI.RadMultiPage
    
    '''<summary>
    '''RadPageView5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView5 As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''RadLabel54 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel54 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadLabel55 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel55 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDatePicker15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker15 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadLabel56 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel56 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox18 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel57 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel57 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox19 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel58 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel58 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox20 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel59 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel59 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDropDownList7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDropDownList7 As Global.Telerik.Web.UI.RadDropDownList
    
    '''<summary>
    '''RadLabel60 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel60 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadLabel61 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel61 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadioButton3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButton3 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadioButton4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButton4 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadioButton5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButton5 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadioButton6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButton6 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadLabel62 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel62 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''FileUpload6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUpload6 As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''RadLabel119 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel119 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadLabel120 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel120 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDatePicker12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker12 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadLabel121 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel121 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDatePicker13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker13 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadLabel125 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel125 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox21 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadPageView6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView6 As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''RadLabel122 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel122 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadLabel63 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel63 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDatePicker3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker3 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadLabel64 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel64 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDatePicker4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker4 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadLabel65 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel65 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDatePicker5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker5 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadLabel66 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel66 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDatePicker6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker6 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadLabel67 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel67 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDatePicker11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker11 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadPageView7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView7 As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''RadLabel126 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel126 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadLabel69 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel69 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDatePicker14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker14 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadLabel70 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel70 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDropDownList9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDropDownList9 As Global.Telerik.Web.UI.RadDropDownList
    
    '''<summary>
    '''RadLabel71 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel71 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDropDownList10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDropDownList10 As Global.Telerik.Web.UI.RadDropDownList
    
    '''<summary>
    '''RadLabel72 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel72 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDatePicker16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker16 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadLabel73 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel73 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadLabel74 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel74 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDatePicker17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker17 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadLabel75 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel75 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''FileUpload7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUpload7 As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''RadLabel76 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel76 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDatePicker18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker18 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadLabel77 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel77 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDatePicker19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker19 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadLabel123 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel123 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox4 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel124 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel124 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox5 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel68 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel68 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''FileUpload12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUpload12 As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''RadPageView8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView8 As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''RadLabel78 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel78 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadLabel79 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel79 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox22 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel93 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel93 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox37 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox37 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel80 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel80 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox59 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox59 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel114 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel114 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox58 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox58 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel81 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel81 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox26 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel82 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel82 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox25 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel83 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel83 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox27 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel84 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel84 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox28 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel85 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel85 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox29 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel86 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel86 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox30 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel87 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel87 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox31 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel88 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel88 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox32 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox32 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel89 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel89 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox33 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox33 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel90 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel90 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox34 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox34 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel91 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel91 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox35 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox35 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel92 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel92 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox36 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox36 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel94 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel94 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox38 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox38 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel95 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel95 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox39 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox39 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel96 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel96 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox40 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox40 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel97 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel97 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox41 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox41 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel98 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel98 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox42 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox42 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel99 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel99 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox43 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox43 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel100 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel100 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox44 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox44 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel101 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel101 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox45 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox45 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel102 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel102 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox46 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox46 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel103 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel103 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox47 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox47 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadPageView9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView9 As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''TextBox6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox6 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RadTreeView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTreeView1 As Global.Telerik.Web.UI.RadTreeView
    
    '''<summary>
    '''RadLabel104 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel104 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox24 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel105 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel105 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox48 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox48 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel106 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel106 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox49 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox49 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel107 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel107 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox50 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox50 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel108 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel108 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadLabel109 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel109 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadLabel110 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel110 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadLabel111 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel111 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox51 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox51 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel112 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel112 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox52 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox52 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''CheckBox3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox3 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''RadTextBox53 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox53 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''CheckBox4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox4 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''RadTextBox54 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox54 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel113 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel113 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadLabel115 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel115 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox55 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox55 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel116 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel116 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox56 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox56 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadLabel117 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel117 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''CheckBox5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox5 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CheckBox6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox6 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''block control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents block As Global.Telerik.Web.UI.RadCodeBlock
    
    '''<summary>
    '''notCampos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents notCampos As Global.Telerik.Web.UI.RadNotification
    
    '''<summary>
    '''vsCampos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vsCampos As Global.System.Web.UI.WebControls.ValidationSummary
    
    '''<summary>
    '''UpdatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblMensaje control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMensaje As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UpdatePanel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel3 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''cmdAceptar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAceptar As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''cmdCancelar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdCancelar As Global.System.Web.UI.WebControls.ImageButton
End Class
