'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Fechas
    
    '''<summary>
    '''ralLoad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ralLoad As Global.Telerik.Web.UI.RadAjaxLoadingPanel
    
    '''<summary>
    '''ramManajer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ramManajer As Global.Telerik.Web.UI.RadAjaxManager
    
    '''<summary>
    '''rapContenedor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rapContenedor As Global.Telerik.Web.UI.RadAjaxPanel
    
    '''<summary>
    '''btnCuentas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCuentas As Global.Telerik.Web.UI.RadToolBar
    
    '''<summary>
    '''TextBox7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox7 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RadTreeView2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTreeView2 As Global.Telerik.Web.UI.RadTreeView
    
    '''<summary>
    '''RadCheckBox2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox2 As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''RadGrid2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGrid2 As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''RadCheckBox3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox3 As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''RadCheckBox4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox4 As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''RadCheckBox5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox5 As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''RadCheckBox6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox6 As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''RadCheckBox7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox7 As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''RadCheckBox8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox8 As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''RadCheckBox9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox9 As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''RadCheckBox10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox10 As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''RadCheckBox11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox11 As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''RadCheckBox12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox12 As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''RadCheckBox13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox13 As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''RadCheckBox14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox14 As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''RadCheckBox15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox15 As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''RadCheckBox16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox16 As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''RadCheckBox17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox17 As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''RadCheckBox18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox18 As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''RadCheckBox19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox19 As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''RadCheckBox20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox20 As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''RadCheckBox21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox21 As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''RadCheckBox22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox22 As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''RadCheckBox23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox23 As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''RadCheckBox24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox24 As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''RadCheckBox25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox25 As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''RadLabel9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel9 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox1 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''block control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents block As Global.Telerik.Web.UI.RadCodeBlock
    
    '''<summary>
    '''notCampos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents notCampos As Global.Telerik.Web.UI.RadNotification
    
    '''<summary>
    '''vsCampos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vsCampos As Global.System.Web.UI.WebControls.ValidationSummary
    
    '''<summary>
    '''UpdatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblMensaje control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMensaje As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UpdatePanel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel3 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''cmdAceptar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAceptar As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''cmdCancelar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdCancelar As Global.System.Web.UI.WebControls.ImageButton
End Class
