'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Temas
    
    '''<summary>
    '''ralLoad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ralLoad As Global.Telerik.Web.UI.RadAjaxLoadingPanel
    
    '''<summary>
    '''ramManajer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ramManajer As Global.Telerik.Web.UI.RadAjaxManager
    
    '''<summary>
    '''rapContenedor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rapContenedor As Global.Telerik.Web.UI.RadAjaxPanel
    
    '''<summary>
    '''btnCuentas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCuentas As Global.Telerik.Web.UI.RadToolBar
    
    '''<summary>
    '''TextBox6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox6 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RadTreeView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTreeView1 As Global.Telerik.Web.UI.RadTreeView
    
    '''<summary>
    '''RadCheckBox15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox15 As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''RadTreeView3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTreeView3 As Global.Telerik.Web.UI.RadTreeView
    
    '''<summary>
    '''RadCheckBox16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox16 As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''RadDropDownList9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDropDownList9 As Global.Telerik.Web.UI.RadDropDownList
    
    '''<summary>
    '''RadTabStrip1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTabStrip1 As Global.Telerik.Web.UI.RadTabStrip
    
    '''<summary>
    '''RadMultiPage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadMultiPage1 As Global.Telerik.Web.UI.RadMultiPage
    
    '''<summary>
    '''RadPageView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView1 As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''RadLabel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel2 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadLabel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel3 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadCheckBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox1 As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''RadDatePicker1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker1 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadDatePicker2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker2 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadLabel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel4 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDropDownList1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDropDownList1 As Global.Telerik.Web.UI.RadDropDownList
    
    '''<summary>
    '''RadLabel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel5 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDropDownList2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDropDownList2 As Global.Telerik.Web.UI.RadDropDownList
    
    '''<summary>
    '''RadLabel6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel6 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDropDownList3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDropDownList3 As Global.Telerik.Web.UI.RadDropDownList
    
    '''<summary>
    '''RadGrid1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGrid1 As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''RadPageView2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView2 As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''RadLabel7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel7 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadLabel8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel8 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadCheckBox2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox2 As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''RadDatePicker3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker3 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadDatePicker4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker4 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadLabel9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel9 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDatePicker5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker5 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadDatePicker6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker6 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadLabel10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel10 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDropDownList5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDropDownList5 As Global.Telerik.Web.UI.RadDropDownList
    
    '''<summary>
    '''RadLabel12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel12 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDropDownList4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDropDownList4 As Global.Telerik.Web.UI.RadDropDownList
    
    '''<summary>
    '''RadLabel13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel13 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDropDownList7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDropDownList7 As Global.Telerik.Web.UI.RadDropDownList
    
    '''<summary>
    '''RadLabel11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel11 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDropDownList6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDropDownList6 As Global.Telerik.Web.UI.RadDropDownList
    
    '''<summary>
    '''RadLabel14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel14 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadLabel15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel15 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadLabel16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel16 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDatePicker7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker7 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadDatePicker8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker8 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadLabel17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel17 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDatePicker9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker9 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadDatePicker10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker10 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadLabel18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel18 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDatePicker11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker11 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadDatePicker12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker12 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadLabel19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel19 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadDatePicker13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker13 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadDatePicker14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker14 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadGrid3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGrid3 As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''RadPageView3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView3 As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''RadCheckBox3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox3 As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''RadTextBox2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox2 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadCheckBox4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox4 As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''RadDatePicker15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker15 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadDatePicker16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker16 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadCheckBox17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox17 As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''RadDropDownList10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDropDownList10 As Global.Telerik.Web.UI.RadDropDownList
    
    '''<summary>
    '''RadGrid4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGrid4 As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''RadPageView4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView4 As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''RadCheckBox5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox5 As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''RadTextBox3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox3 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadCheckBox6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox6 As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''RadDropDownList8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDropDownList8 As Global.Telerik.Web.UI.RadDropDownList
    
    '''<summary>
    '''RadLabel20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel20 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadLabel21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel21 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadCheckBox7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox7 As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''RadDatePicker17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker17 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadDatePicker18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker18 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadCheckBox8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox8 As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''RadDatePicker19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker19 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadDatePicker20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker20 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadCheckBox9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox9 As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''RadDatePicker21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker21 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadDatePicker22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker22 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadCheckBox10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox10 As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''RadDatePicker23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker23 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadDatePicker24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker24 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadCheckBox11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox11 As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''RadDatePicker25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker25 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadDatePicker26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker26 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadCheckBox12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox12 As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''RadDatePicker27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker27 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadDatePicker28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker28 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadCheckBox13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox13 As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''RadDatePicker29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker29 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadDatePicker30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker30 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadCheckBox14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCheckBox14 As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''RadDatePicker31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker31 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadDatePicker32 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePicker32 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadLabel22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel22 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox4 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''RadGrid5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGrid5 As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''RadLabel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLabel1 As Global.Telerik.Web.UI.RadLabel
    
    '''<summary>
    '''RadTextBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTextBox1 As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''block control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents block As Global.Telerik.Web.UI.RadCodeBlock
    
    '''<summary>
    '''notCampos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents notCampos As Global.Telerik.Web.UI.RadNotification
    
    '''<summary>
    '''vsCampos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vsCampos As Global.System.Web.UI.WebControls.ValidationSummary
    
    '''<summary>
    '''UpdatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblMensaje control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMensaje As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UpdatePanel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel3 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''cmdAceptar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAceptar As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''cmdCancelar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdCancelar As Global.System.Web.UI.WebControls.ImageButton
End Class
