//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("NormanetRestrucModel", "FK__C_Comites__Activ__70DDC3D8", "C_Comites", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Conexion_Normanet.ContextoAnce.C_Comites), "C_ComitesTecnicos", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Conexion_Normanet.ContextoAnce.C_ComitesTecnicos))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("NormanetRestrucModel", "FK__C_GruposT__Activ__7A672E12", "C_Comites", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Conexion_Normanet.ContextoAnce.C_Comites), "C_GruposTrabajo", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Conexion_Normanet.ContextoAnce.C_GruposTrabajo))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("NormanetRestrucModel", "FK__C_GruposT__IdCom__7B5B524B", "C_ComitesTecnicos", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Conexion_Normanet.ContextoAnce.C_ComitesTecnicos), "C_GruposTrabajo", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Conexion_Normanet.ContextoAnce.C_GruposTrabajo))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("NormanetRestrucModel", "FK__C_SubComi__Activ__75A278F5", "C_ComitesTecnicos", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Conexion_Normanet.ContextoAnce.C_ComitesTecnicos), "C_SubComites", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Conexion_Normanet.ContextoAnce.C_SubComites))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("NormanetRestrucModel", "FK__C_GruposT__IdSub__7C4F7684", "C_SubComites", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Conexion_Normanet.ContextoAnce.C_SubComites), "C_GruposTrabajo", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Conexion_Normanet.ContextoAnce.C_GruposTrabajo))]

// Nombre de archivo original:
// Fecha de generación: 24/01/2021 08:55:40 p. m.
namespace Conexion_Normanet.ContextoAnce
{
    
    /// <summary>
    /// No hay ningún comentario para NormanetRestrucModel.C_Comites en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// IdComite
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="NormanetRestrucModel", Name="C_Comites")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class C_Comites : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto C_Comites.
        /// </summary>
        /// <param name="idComite">Valor inicial de IdComite.</param>
        /// <param name="comite">Valor inicial de Comite.</param>
        /// <param name="idUsuarioResponsable">Valor inicial de IdUsuarioResponsable.</param>
        /// <param name="fechaAlta">Valor inicial de FechaAlta.</param>
        /// <param name="activo">Valor inicial de Activo.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static C_Comites CreateC_Comites(int idComite, string comite, string idUsuarioResponsable, global::System.DateTime fechaAlta, bool activo)
        {
            C_Comites c_Comites = new C_Comites();
            c_Comites.IdComite = idComite;
            c_Comites.Comite = comite;
            c_Comites.IdUsuarioResponsable = idUsuarioResponsable;
            c_Comites.FechaAlta = fechaAlta;
            c_Comites.Activo = activo;
            return c_Comites;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad IdComite en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int IdComite
        {
            get
            {
                return this._IdComite;
            }
            set
            {
                this.OnIdComiteChanging(value);
                this.ReportPropertyChanging("IdComite");
                this._IdComite = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdComite");
                this.OnIdComiteChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _IdComite;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdComiteChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdComiteChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Comite en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Comite
        {
            get
            {
                return this._Comite;
            }
            set
            {
                this.OnComiteChanging(value);
                this.ReportPropertyChanging("Comite");
                this._Comite = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Comite");
                this.OnComiteChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Comite;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnComiteChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnComiteChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Alcance en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Alcance
        {
            get
            {
                return this._Alcance;
            }
            set
            {
                this.OnAlcanceChanging(value);
                this.ReportPropertyChanging("Alcance");
                this._Alcance = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Alcance");
                this.OnAlcanceChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Alcance;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnAlcanceChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnAlcanceChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad IdUsuarioResponsable en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string IdUsuarioResponsable
        {
            get
            {
                return this._IdUsuarioResponsable;
            }
            set
            {
                this.OnIdUsuarioResponsableChanging(value);
                this.ReportPropertyChanging("IdUsuarioResponsable");
                this._IdUsuarioResponsable = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("IdUsuarioResponsable");
                this.OnIdUsuarioResponsableChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _IdUsuarioResponsable;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdUsuarioResponsableChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdUsuarioResponsableChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Objetivo en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Objetivo
        {
            get
            {
                return this._Objetivo;
            }
            set
            {
                this.OnObjetivoChanging(value);
                this.ReportPropertyChanging("Objetivo");
                this._Objetivo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Objetivo");
                this.OnObjetivoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Objetivo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnObjetivoChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnObjetivoChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad FechaAlta en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.DateTime FechaAlta
        {
            get
            {
                return this._FechaAlta;
            }
            set
            {
                this.OnFechaAltaChanging(value);
                this.ReportPropertyChanging("FechaAlta");
                this._FechaAlta = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("FechaAlta");
                this.OnFechaAltaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.DateTime _FechaAlta;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFechaAltaChanging(global::System.DateTime value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFechaAltaChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Activo en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public bool Activo
        {
            get
            {
                return this._Activo;
            }
            set
            {
                this.OnActivoChanging(value);
                this.ReportPropertyChanging("Activo");
                this._Activo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Activo");
                this.OnActivoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private bool _Activo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnActivoChanging(bool value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnActivoChanged();
        /// <summary>
        /// No hay ningún comentario para C_ComitesTecnicos en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("NormanetRestrucModel", "FK__C_Comites__Activ__70DDC3D8", "C_ComitesTecnicos")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<C_ComitesTecnicos> C_ComitesTecnicos
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<C_ComitesTecnicos>("NormanetRestrucModel.FK__C_Comites__Activ__70DDC3D8", "C_ComitesTecnicos");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<C_ComitesTecnicos>("NormanetRestrucModel.FK__C_Comites__Activ__70DDC3D8", "C_ComitesTecnicos", value);
                }
            }
        }
        /// <summary>
        /// No hay ningún comentario para C_GruposTrabajo en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("NormanetRestrucModel", "FK__C_GruposT__Activ__7A672E12", "C_GruposTrabajo")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<C_GruposTrabajo> C_GruposTrabajo
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<C_GruposTrabajo>("NormanetRestrucModel.FK__C_GruposT__Activ__7A672E12", "C_GruposTrabajo");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<C_GruposTrabajo>("NormanetRestrucModel.FK__C_GruposT__Activ__7A672E12", "C_GruposTrabajo", value);
                }
            }
        }
    }
    /// <summary>
    /// No hay ningún comentario para NormanetRestrucEntities en el esquema.
    /// </summary>
    public partial class NormanetRestrucEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Inicializa un nuevo objeto NormanetRestrucEntities usando la cadena de conexión encontrada en la sección 'NormanetRestrucEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public NormanetRestrucEntities() : 
                base("name=NormanetRestrucEntities", "NormanetRestrucEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Inicializar un nuevo objeto NormanetRestrucEntities.
        /// </summary>
        public NormanetRestrucEntities(string connectionString) : 
                base(connectionString, "NormanetRestrucEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Inicializar un nuevo objeto NormanetRestrucEntities.
        /// </summary>
        public NormanetRestrucEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "NormanetRestrucEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// No hay ningún comentario para C_Comites en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<C_Comites> C_Comites
        {
            get
            {
                if ((this._C_Comites == null))
                {
                    this._C_Comites = base.CreateQuery<C_Comites>("[C_Comites]");
                }
                return this._C_Comites;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<C_Comites> _C_Comites;
        /// <summary>
        /// No hay ningún comentario para C_ComitesTecnicos en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<C_ComitesTecnicos> C_ComitesTecnicos
        {
            get
            {
                if ((this._C_ComitesTecnicos == null))
                {
                    this._C_ComitesTecnicos = base.CreateQuery<C_ComitesTecnicos>("[C_ComitesTecnicos]");
                }
                return this._C_ComitesTecnicos;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<C_ComitesTecnicos> _C_ComitesTecnicos;
        /// <summary>
        /// No hay ningún comentario para C_GruposTrabajo en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<C_GruposTrabajo> C_GruposTrabajo
        {
            get
            {
                if ((this._C_GruposTrabajo == null))
                {
                    this._C_GruposTrabajo = base.CreateQuery<C_GruposTrabajo>("[C_GruposTrabajo]");
                }
                return this._C_GruposTrabajo;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<C_GruposTrabajo> _C_GruposTrabajo;
        /// <summary>
        /// No hay ningún comentario para C_SubComites en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<C_SubComites> C_SubComites
        {
            get
            {
                if ((this._C_SubComites == null))
                {
                    this._C_SubComites = base.CreateQuery<C_SubComites>("[C_SubComites]");
                }
                return this._C_SubComites;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<C_SubComites> _C_SubComites;
        /// <summary>
        /// No hay ningún comentario para C_Comites en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToC_Comites(C_Comites c_Comites)
        {
            base.AddObject("C_Comites", c_Comites);
        }
        /// <summary>
        /// No hay ningún comentario para C_ComitesTecnicos en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToC_ComitesTecnicos(C_ComitesTecnicos c_ComitesTecnicos)
        {
            base.AddObject("C_ComitesTecnicos", c_ComitesTecnicos);
        }
        /// <summary>
        /// No hay ningún comentario para C_GruposTrabajo en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToC_GruposTrabajo(C_GruposTrabajo c_GruposTrabajo)
        {
            base.AddObject("C_GruposTrabajo", c_GruposTrabajo);
        }
        /// <summary>
        /// No hay ningún comentario para C_SubComites en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToC_SubComites(C_SubComites c_SubComites)
        {
            base.AddObject("C_SubComites", c_SubComites);
        }
        /// <summary>
        /// No hay ningún comentario para NormanetRestrucEntities.uspComites en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectResult<C_Comites> uspComites(string bANDERA, global::System.Nullable<int> idcomite, global::System.Nullable<int> idcomitetecnico, global::System.Nullable<int> idSubComite)
        {
            global::System.Data.Objects.ObjectParameter bANDERAParameter;
            if ((bANDERA != null))
            {
                bANDERAParameter = new global::System.Data.Objects.ObjectParameter("BANDERA", bANDERA);
            }
            else
            {
                bANDERAParameter = new global::System.Data.Objects.ObjectParameter("BANDERA", typeof(string));
            }
            global::System.Data.Objects.ObjectParameter idcomiteParameter;
            if (idcomite.HasValue)
            {
                idcomiteParameter = new global::System.Data.Objects.ObjectParameter("idcomite", idcomite);
            }
            else
            {
                idcomiteParameter = new global::System.Data.Objects.ObjectParameter("idcomite", typeof(int));
            }
            global::System.Data.Objects.ObjectParameter idcomitetecnicoParameter;
            if (idcomitetecnico.HasValue)
            {
                idcomitetecnicoParameter = new global::System.Data.Objects.ObjectParameter("idcomitetecnico", idcomitetecnico);
            }
            else
            {
                idcomitetecnicoParameter = new global::System.Data.Objects.ObjectParameter("idcomitetecnico", typeof(int));
            }
            global::System.Data.Objects.ObjectParameter idSubComiteParameter;
            if (idSubComite.HasValue)
            {
                idSubComiteParameter = new global::System.Data.Objects.ObjectParameter("IdSubComite", idSubComite);
            }
            else
            {
                idSubComiteParameter = new global::System.Data.Objects.ObjectParameter("IdSubComite", typeof(int));
            }
            return base.ExecuteFunction<C_Comites>("uspComites", bANDERAParameter, idcomiteParameter, idcomitetecnicoParameter, idSubComiteParameter);
        }
        /// <summary>
        /// No hay ningún comentario para NormanetRestrucEntities.Get_comites en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectResult<C_Comites> Get_comites(string bANDERA, global::System.Nullable<int> idcomite, global::System.Nullable<int> idcomitetecnico, global::System.Nullable<int> idSubComite)
        {
            global::System.Data.Objects.ObjectParameter bANDERAParameter;
            if ((bANDERA != null))
            {
                bANDERAParameter = new global::System.Data.Objects.ObjectParameter("BANDERA", bANDERA);
            }
            else
            {
                bANDERAParameter = new global::System.Data.Objects.ObjectParameter("BANDERA", typeof(string));
            }
            global::System.Data.Objects.ObjectParameter idcomiteParameter;
            if (idcomite.HasValue)
            {
                idcomiteParameter = new global::System.Data.Objects.ObjectParameter("idcomite", idcomite);
            }
            else
            {
                idcomiteParameter = new global::System.Data.Objects.ObjectParameter("idcomite", typeof(int));
            }
            global::System.Data.Objects.ObjectParameter idcomitetecnicoParameter;
            if (idcomitetecnico.HasValue)
            {
                idcomitetecnicoParameter = new global::System.Data.Objects.ObjectParameter("idcomitetecnico", idcomitetecnico);
            }
            else
            {
                idcomitetecnicoParameter = new global::System.Data.Objects.ObjectParameter("idcomitetecnico", typeof(int));
            }
            global::System.Data.Objects.ObjectParameter idSubComiteParameter;
            if (idSubComite.HasValue)
            {
                idSubComiteParameter = new global::System.Data.Objects.ObjectParameter("IdSubComite", idSubComite);
            }
            else
            {
                idSubComiteParameter = new global::System.Data.Objects.ObjectParameter("IdSubComite", typeof(int));
            }
            return base.ExecuteFunction<C_Comites>("Get_comites", bANDERAParameter, idcomiteParameter, idcomitetecnicoParameter, idSubComiteParameter);
        }
        /// <summary>
        /// No hay ningún comentario para NormanetRestrucEntities.Get_Comites_Tecnicos en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectResult<C_ComitesTecnicos> Get_Comites_Tecnicos(string bANDERA, global::System.Nullable<int> idcomite, global::System.Nullable<int> idcomitetecnico, global::System.Nullable<int> idSubComite)
        {
            global::System.Data.Objects.ObjectParameter bANDERAParameter;
            if ((bANDERA != null))
            {
                bANDERAParameter = new global::System.Data.Objects.ObjectParameter("BANDERA", bANDERA);
            }
            else
            {
                bANDERAParameter = new global::System.Data.Objects.ObjectParameter("BANDERA", typeof(string));
            }
            global::System.Data.Objects.ObjectParameter idcomiteParameter;
            if (idcomite.HasValue)
            {
                idcomiteParameter = new global::System.Data.Objects.ObjectParameter("idcomite", idcomite);
            }
            else
            {
                idcomiteParameter = new global::System.Data.Objects.ObjectParameter("idcomite", typeof(int));
            }
            global::System.Data.Objects.ObjectParameter idcomitetecnicoParameter;
            if (idcomitetecnico.HasValue)
            {
                idcomitetecnicoParameter = new global::System.Data.Objects.ObjectParameter("idcomitetecnico", idcomitetecnico);
            }
            else
            {
                idcomitetecnicoParameter = new global::System.Data.Objects.ObjectParameter("idcomitetecnico", typeof(int));
            }
            global::System.Data.Objects.ObjectParameter idSubComiteParameter;
            if (idSubComite.HasValue)
            {
                idSubComiteParameter = new global::System.Data.Objects.ObjectParameter("IdSubComite", idSubComite);
            }
            else
            {
                idSubComiteParameter = new global::System.Data.Objects.ObjectParameter("IdSubComite", typeof(int));
            }
            return base.ExecuteFunction<C_ComitesTecnicos>("Get_Comites_Tecnicos", bANDERAParameter, idcomiteParameter, idcomitetecnicoParameter, idSubComiteParameter);
        }
    }
    /// <summary>
    /// No hay ningún comentario para NormanetRestrucModel.C_ComitesTecnicos en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// IdComiteTecnico
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="NormanetRestrucModel", Name="C_ComitesTecnicos")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class C_ComitesTecnicos : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto C_ComitesTecnicos.
        /// </summary>
        /// <param name="idComiteTecnico">Valor inicial de IdComiteTecnico.</param>
        /// <param name="comiteTecnico">Valor inicial de ComiteTecnico.</param>
        /// <param name="idUsuarioResponsable">Valor inicial de IdUsuarioResponsable.</param>
        /// <param name="fechaAlta">Valor inicial de FechaAlta.</param>
        /// <param name="activo">Valor inicial de Activo.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static C_ComitesTecnicos CreateC_ComitesTecnicos(int idComiteTecnico, string comiteTecnico, string idUsuarioResponsable, global::System.DateTime fechaAlta, bool activo)
        {
            C_ComitesTecnicos c_ComitesTecnicos = new C_ComitesTecnicos();
            c_ComitesTecnicos.IdComiteTecnico = idComiteTecnico;
            c_ComitesTecnicos.ComiteTecnico = comiteTecnico;
            c_ComitesTecnicos.IdUsuarioResponsable = idUsuarioResponsable;
            c_ComitesTecnicos.FechaAlta = fechaAlta;
            c_ComitesTecnicos.Activo = activo;
            return c_ComitesTecnicos;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad IdComiteTecnico en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int IdComiteTecnico
        {
            get
            {
                return this._IdComiteTecnico;
            }
            set
            {
                this.OnIdComiteTecnicoChanging(value);
                this.ReportPropertyChanging("IdComiteTecnico");
                this._IdComiteTecnico = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdComiteTecnico");
                this.OnIdComiteTecnicoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _IdComiteTecnico;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdComiteTecnicoChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdComiteTecnicoChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad ComiteTecnico en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string ComiteTecnico
        {
            get
            {
                return this._ComiteTecnico;
            }
            set
            {
                this.OnComiteTecnicoChanging(value);
                this.ReportPropertyChanging("ComiteTecnico");
                this._ComiteTecnico = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ComiteTecnico");
                this.OnComiteTecnicoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _ComiteTecnico;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnComiteTecnicoChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnComiteTecnicoChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad IdUsuarioResponsable en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string IdUsuarioResponsable
        {
            get
            {
                return this._IdUsuarioResponsable;
            }
            set
            {
                this.OnIdUsuarioResponsableChanging(value);
                this.ReportPropertyChanging("IdUsuarioResponsable");
                this._IdUsuarioResponsable = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("IdUsuarioResponsable");
                this.OnIdUsuarioResponsableChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _IdUsuarioResponsable;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdUsuarioResponsableChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdUsuarioResponsableChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Objetivo en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Objetivo
        {
            get
            {
                return this._Objetivo;
            }
            set
            {
                this.OnObjetivoChanging(value);
                this.ReportPropertyChanging("Objetivo");
                this._Objetivo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Objetivo");
                this.OnObjetivoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Objetivo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnObjetivoChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnObjetivoChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad FechaAlta en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.DateTime FechaAlta
        {
            get
            {
                return this._FechaAlta;
            }
            set
            {
                this.OnFechaAltaChanging(value);
                this.ReportPropertyChanging("FechaAlta");
                this._FechaAlta = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("FechaAlta");
                this.OnFechaAltaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.DateTime _FechaAlta;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFechaAltaChanging(global::System.DateTime value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFechaAltaChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Activo en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public bool Activo
        {
            get
            {
                return this._Activo;
            }
            set
            {
                this.OnActivoChanging(value);
                this.ReportPropertyChanging("Activo");
                this._Activo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Activo");
                this.OnActivoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private bool _Activo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnActivoChanging(bool value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnActivoChanged();
        /// <summary>
        /// No hay ningún comentario para C_GruposTrabajo en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("NormanetRestrucModel", "FK__C_GruposT__IdCom__7B5B524B", "C_GruposTrabajo")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<C_GruposTrabajo> C_GruposTrabajo
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<C_GruposTrabajo>("NormanetRestrucModel.FK__C_GruposT__IdCom__7B5B524B", "C_GruposTrabajo");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<C_GruposTrabajo>("NormanetRestrucModel.FK__C_GruposT__IdCom__7B5B524B", "C_GruposTrabajo", value);
                }
            }
        }
        /// <summary>
        /// No hay ningún comentario para C_SubComites en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("NormanetRestrucModel", "FK__C_SubComi__Activ__75A278F5", "C_SubComites")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<C_SubComites> C_SubComites
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<C_SubComites>("NormanetRestrucModel.FK__C_SubComi__Activ__75A278F5", "C_SubComites");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<C_SubComites>("NormanetRestrucModel.FK__C_SubComi__Activ__75A278F5", "C_SubComites", value);
                }
            }
        }
    }
    /// <summary>
    /// No hay ningún comentario para NormanetRestrucModel.C_GruposTrabajo en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// IdGrupoTrabajo
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="NormanetRestrucModel", Name="C_GruposTrabajo")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class C_GruposTrabajo : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto C_GruposTrabajo.
        /// </summary>
        /// <param name="idGrupoTrabajo">Valor inicial de IdGrupoTrabajo.</param>
        /// <param name="grupoTrabajo">Valor inicial de GrupoTrabajo.</param>
        /// <param name="idUsuarioResponsable">Valor inicial de IdUsuarioResponsable.</param>
        /// <param name="fechaAlta">Valor inicial de FechaAlta.</param>
        /// <param name="activo">Valor inicial de Activo.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static C_GruposTrabajo CreateC_GruposTrabajo(int idGrupoTrabajo, string grupoTrabajo, string idUsuarioResponsable, global::System.DateTime fechaAlta, bool activo)
        {
            C_GruposTrabajo c_GruposTrabajo = new C_GruposTrabajo();
            c_GruposTrabajo.IdGrupoTrabajo = idGrupoTrabajo;
            c_GruposTrabajo.GrupoTrabajo = grupoTrabajo;
            c_GruposTrabajo.IdUsuarioResponsable = idUsuarioResponsable;
            c_GruposTrabajo.FechaAlta = fechaAlta;
            c_GruposTrabajo.Activo = activo;
            return c_GruposTrabajo;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad IdGrupoTrabajo en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int IdGrupoTrabajo
        {
            get
            {
                return this._IdGrupoTrabajo;
            }
            set
            {
                this.OnIdGrupoTrabajoChanging(value);
                this.ReportPropertyChanging("IdGrupoTrabajo");
                this._IdGrupoTrabajo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdGrupoTrabajo");
                this.OnIdGrupoTrabajoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _IdGrupoTrabajo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdGrupoTrabajoChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdGrupoTrabajoChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad GrupoTrabajo en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string GrupoTrabajo
        {
            get
            {
                return this._GrupoTrabajo;
            }
            set
            {
                this.OnGrupoTrabajoChanging(value);
                this.ReportPropertyChanging("GrupoTrabajo");
                this._GrupoTrabajo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("GrupoTrabajo");
                this.OnGrupoTrabajoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _GrupoTrabajo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnGrupoTrabajoChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnGrupoTrabajoChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad IdUsuarioResponsable en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string IdUsuarioResponsable
        {
            get
            {
                return this._IdUsuarioResponsable;
            }
            set
            {
                this.OnIdUsuarioResponsableChanging(value);
                this.ReportPropertyChanging("IdUsuarioResponsable");
                this._IdUsuarioResponsable = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("IdUsuarioResponsable");
                this.OnIdUsuarioResponsableChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _IdUsuarioResponsable;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdUsuarioResponsableChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdUsuarioResponsableChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Objetivo en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Objetivo
        {
            get
            {
                return this._Objetivo;
            }
            set
            {
                this.OnObjetivoChanging(value);
                this.ReportPropertyChanging("Objetivo");
                this._Objetivo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Objetivo");
                this.OnObjetivoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Objetivo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnObjetivoChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnObjetivoChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad FechaAlta en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.DateTime FechaAlta
        {
            get
            {
                return this._FechaAlta;
            }
            set
            {
                this.OnFechaAltaChanging(value);
                this.ReportPropertyChanging("FechaAlta");
                this._FechaAlta = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("FechaAlta");
                this.OnFechaAltaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.DateTime _FechaAlta;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFechaAltaChanging(global::System.DateTime value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFechaAltaChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Activo en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public bool Activo
        {
            get
            {
                return this._Activo;
            }
            set
            {
                this.OnActivoChanging(value);
                this.ReportPropertyChanging("Activo");
                this._Activo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Activo");
                this.OnActivoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private bool _Activo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnActivoChanging(bool value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnActivoChanged();
        /// <summary>
        /// No hay ningún comentario para C_SubComites en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("NormanetRestrucModel", "FK__C_GruposT__IdSub__7C4F7684", "C_SubComites")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public C_SubComites C_SubComites
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<C_SubComites>("NormanetRestrucModel.FK__C_GruposT__IdSub__7C4F7684", "C_SubComites").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<C_SubComites>("NormanetRestrucModel.FK__C_GruposT__IdSub__7C4F7684", "C_SubComites").Value = value;
            }
        }
        /// <summary>
        /// No hay ningún comentario para C_SubComites en el esquema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<C_SubComites> C_SubComitesReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<C_SubComites>("NormanetRestrucModel.FK__C_GruposT__IdSub__7C4F7684", "C_SubComites");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<C_SubComites>("NormanetRestrucModel.FK__C_GruposT__IdSub__7C4F7684", "C_SubComites", value);
                }
            }
        }
    }
    /// <summary>
    /// No hay ningún comentario para NormanetRestrucModel.C_SubComites en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// IdSubComite
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="NormanetRestrucModel", Name="C_SubComites")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class C_SubComites : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto C_SubComites.
        /// </summary>
        /// <param name="idSubComite">Valor inicial de IdSubComite.</param>
        /// <param name="subComite">Valor inicial de SubComite.</param>
        /// <param name="idUsuarioResponsable">Valor inicial de IdUsuarioResponsable.</param>
        /// <param name="fechaAlta">Valor inicial de FechaAlta.</param>
        /// <param name="activo">Valor inicial de Activo.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static C_SubComites CreateC_SubComites(int idSubComite, string subComite, string idUsuarioResponsable, global::System.DateTime fechaAlta, bool activo)
        {
            C_SubComites c_SubComites = new C_SubComites();
            c_SubComites.IdSubComite = idSubComite;
            c_SubComites.SubComite = subComite;
            c_SubComites.IdUsuarioResponsable = idUsuarioResponsable;
            c_SubComites.FechaAlta = fechaAlta;
            c_SubComites.Activo = activo;
            return c_SubComites;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad IdSubComite en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int IdSubComite
        {
            get
            {
                return this._IdSubComite;
            }
            set
            {
                this.OnIdSubComiteChanging(value);
                this.ReportPropertyChanging("IdSubComite");
                this._IdSubComite = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdSubComite");
                this.OnIdSubComiteChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _IdSubComite;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdSubComiteChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdSubComiteChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad SubComite en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string SubComite
        {
            get
            {
                return this._SubComite;
            }
            set
            {
                this.OnSubComiteChanging(value);
                this.ReportPropertyChanging("SubComite");
                this._SubComite = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("SubComite");
                this.OnSubComiteChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _SubComite;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSubComiteChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSubComiteChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad IdUsuarioResponsable en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string IdUsuarioResponsable
        {
            get
            {
                return this._IdUsuarioResponsable;
            }
            set
            {
                this.OnIdUsuarioResponsableChanging(value);
                this.ReportPropertyChanging("IdUsuarioResponsable");
                this._IdUsuarioResponsable = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("IdUsuarioResponsable");
                this.OnIdUsuarioResponsableChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _IdUsuarioResponsable;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdUsuarioResponsableChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdUsuarioResponsableChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Objetivo en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Objetivo
        {
            get
            {
                return this._Objetivo;
            }
            set
            {
                this.OnObjetivoChanging(value);
                this.ReportPropertyChanging("Objetivo");
                this._Objetivo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Objetivo");
                this.OnObjetivoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Objetivo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnObjetivoChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnObjetivoChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad FechaAlta en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.DateTime FechaAlta
        {
            get
            {
                return this._FechaAlta;
            }
            set
            {
                this.OnFechaAltaChanging(value);
                this.ReportPropertyChanging("FechaAlta");
                this._FechaAlta = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("FechaAlta");
                this.OnFechaAltaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.DateTime _FechaAlta;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFechaAltaChanging(global::System.DateTime value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFechaAltaChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Activo en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public bool Activo
        {
            get
            {
                return this._Activo;
            }
            set
            {
                this.OnActivoChanging(value);
                this.ReportPropertyChanging("Activo");
                this._Activo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Activo");
                this.OnActivoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private bool _Activo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnActivoChanging(bool value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnActivoChanged();
    }
}
